#!/bin/bash

# Version of the script - checks with my github every time
SCRIPT_VERSION="1.0.0"

# Display the script's own location
echo "Script location: $(dirname $(readlink -f $0))"

# Shows active paths line by line
echo "Active paths are:"
echo $PATH | tr ':' '\n'

# Function to check for updates
check_for_update() {
    echo "Checking for updates..."
    LATEST_VERSION=$(curl -s $VERSION_URL | grep 'SCRIPT_VERSION="' | cut -d '"' -f 2)
    
    if [ "$LATEST_VERSION" != "" ] && [ "$LATEST_VERSION" != "$SCRIPT_VERSION" ]; then
        echo "A new version ($LATEST_VERSION) is available. Seems you made some changes. Current version: $SCRIPT_VERSION"
        echo "Update the script by downloading it from: https://github.com/$GITHUB_USER/$GITHUB_REPO"
    else
#    No need to mention, still function should be present
#    echo "You are using the latest version ($SCRIPT_VERSION)."
    fi
}

# GitHub repository and raw file URL
GITHUB_USER="kappuchino"
GITHUB_REPO="trivial-tools"
GITHUB_FILE="paths"
VERSION_URL="https://raw.githubusercontent.com/$GITHUB_USER/$GITHUB_REPO/main/$GITHUB_FILE"

# Check for updates
check_for_update
